/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.PGADAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.DataFile;
import pojo.PGA;
import pojo.SGA;
import pojo.User;
import pojo.Instance;
import pojo.Database;
import pojo.Policy;
import pojo.Session;
import pojo.Process;
/**
 *
 * @author nbkha
 */
public class frmHeThong extends javax.swing.JDialog {

    /**
     * Creates new form frmHeThong
     */
    PGADAO x=new PGADAO();
    public frmHeThong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Hệ Thống");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDS = new javax.swing.JTable();
        btn_database = new javax.swing.JButton();
        btn_instance = new javax.swing.JButton();
        btn_process = new javax.swing.JButton();
        btn_pga = new javax.swing.JButton();
        btn_sga1 = new javax.swing.JButton();
        btn_datafile = new javax.swing.JButton();
        btn_session = new javax.swing.JButton();
        btnSLSession = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPolicyHienCo = new javax.swing.JButton();
        btnPolicy = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        btnTableSpace = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbDS.setBackground(new java.awt.Color(204, 204, 204));
        tbDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDS);

        btn_database.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_database.setForeground(new java.awt.Color(255, 102, 102));
        btn_database.setText("Database");
        btn_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databaseActionPerformed(evt);
            }
        });

        btn_instance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_instance.setForeground(new java.awt.Color(255, 102, 102));
        btn_instance.setText("Instance");
        btn_instance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_instanceActionPerformed(evt);
            }
        });

        btn_process.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_process.setForeground(new java.awt.Color(255, 102, 102));
        btn_process.setText("Process");
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_pga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_pga.setForeground(new java.awt.Color(255, 102, 102));
        btn_pga.setText("PGA");
        btn_pga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pgaActionPerformed(evt);
            }
        });

        btn_sga1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sga1.setForeground(new java.awt.Color(255, 102, 102));
        btn_sga1.setText("SGA");
        btn_sga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sga1ActionPerformed(evt);
            }
        });

        btn_datafile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_datafile.setForeground(new java.awt.Color(255, 102, 102));
        btn_datafile.setText("DataFile");
        btn_datafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datafileActionPerformed(evt);
            }
        });

        btn_session.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_session.setForeground(new java.awt.Color(255, 102, 102));
        btn_session.setText("Session");
        btn_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sessionActionPerformed(evt);
            }
        });

        btnSLSession.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSLSession.setForeground(new java.awt.Color(255, 102, 102));
        btnSLSession.setText("SL Session");
        btnSLSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSLSessionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kiểm tra Session");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kiểm tra Policy");

        btnPolicyHienCo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPolicyHienCo.setForeground(new java.awt.Color(255, 102, 102));
        btnPolicyHienCo.setText("Policy KT");
        btnPolicyHienCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicyHienCoActionPerformed(evt);
            }
        });

        btnPolicy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPolicy.setForeground(new java.awt.Color(255, 102, 102));
        btnPolicy.setText("Policy QT");
        btnPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicyActionPerformed(evt);
            }
        });

        btn_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_user.setForeground(new java.awt.Color(255, 102, 102));
        btn_user.setText("User");
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        btnTableSpace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTableSpace.setForeground(new java.awt.Color(255, 102, 102));
        btnTableSpace.setText("TableSpace_User");
        btnTableSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableSpaceActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kiểm tra User");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Thông tin hệ thống");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_database, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_process, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPolicyHienCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_instance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_datafile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTableSpace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPolicy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSLSession, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_instance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sga1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_datafile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnTableSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_database, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_pga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_session, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSLSession, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPolicyHienCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databaseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin của Database");
        String col[]={"dbid","name","created","log_mode","open_mode"};
        ArrayList<Database> t=x.LayDSDatabase();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getDBID(),t.get(i).getNAME(),t.get(i).getCREATED(),t.get(i).getLOG_MODE(),t.get(i).getOPEN_MODE()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btn_databaseActionPerformed

    private void btn_instanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_instanceActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin của Instance");
        String col[]={"instance_number","instance_name","host_name","status","parallel"};
        ArrayList<Instance> t=x.LayDSInstance();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getINSTANCE_NUMBER(),t.get(i).getINSTANCE_NAME(),t.get(i).getHOST_NAME(),t.get(i).getSTATUS(),t.get(i).getPARALLEL()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();

    }//GEN-LAST:event_btn_instanceActionPerformed

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin của Process");
        String col[]={"PID","SOSID","SPID","STID"};
        ArrayList<Process> t=x.LayDSProcess();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getPID(),t.get(i).getSOSID(),t.get(i).getSPID(),t.get(i).getSTID()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_pgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pgaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin của PGA");
        String col[]={"Name","Values","Unit","Con_ID"};
        ArrayList<PGA> t=x.LayDS();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getNAME(),t.get(i).getVALUES(),t.get(i).getUNIT(),t.get(i).getCON_ID()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();

    }//GEN-LAST:event_btn_pgaActionPerformed

    private void btn_sga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sga1ActionPerformed
        JOptionPane.showMessageDialog(this, "Thông tin của SGA");
        String col[]={"Name","Bytes","ResizeAble","Con_ID"};
        ArrayList<SGA> t=x.LayDSSGA();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getNAME(),t.get(i).getBYTES(),t.get(i).getRESIZEABLE(),t.get(i).getCON_ID()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btn_sga1ActionPerformed

    private void btn_datafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datafileActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin DataFile");
        String col[]={"FILE#","CREATION_CHANGE#","CREATION_TIME","STATUS","ENABLED","NAME"};
        ArrayList<DataFile> t=x.LayDSDataFile();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getFILE(),t.get(i).getCREATION_CHANGE(),t.get(i).getCREATION_TIME(),t.get(i).getSTATUS(),t.get(i).getENABLED(),t.get(i).getNAME()};
            dtm.addRow(obj);
        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btn_datafileActionPerformed

    private void btn_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sessionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin của Session");
        String col[]={"SID","SERIAL#","AUDSID","USERNAME","PROGRAM"};
        ArrayList<Session> t=x.LayDSSession();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getSID(),t.get(i).getSERIAL(),t.get(i).getAUDSID(),t.get(i).getUSERNAME(),t.get(i).getPROGRAM()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btn_sessionActionPerformed

    private void btnSLSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSLSessionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Số lượng Session");
        String col[]={"Số Lượng Session"};
        ArrayList<Session> t=x.LaySLSession();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getSL()};
            dtm.addRow(obj);
        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btnSLSessionActionPerformed

    private void btnPolicyHienCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicyHienCoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Những  Policy được tạo");
        String col[]={"object_schema","object_name","policy_owner","policy_name"};
        ArrayList<Policy> t=x.LayDSPocilyHienCo();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getOBJECT_SCHEMA(),t.get(i).getOBJECT_NAME(),t.get(i).getPOLICY_OWNER(),t.get(i).getPOLICY_NAME()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btnPolicyHienCoActionPerformed

    private void btnPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Những hoạt động của Policy");
        String col[]={"session_id","db_user","object_name","sql_text","statement_type"};
        ArrayList<Policy> t=x.LayDSHDCuaPolicy();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getSESSION_ID(),t.get(i).getDB_USER(),t.get(i).getOBJECT_NAME(),t.get(i).getSQL_TEXT(),t.get(i).getSTATEMENT_TYPE()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btnPolicyActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin của User");
        String col[]={"USERNAME","CREATED","EXPIRY_DATE","ACCOUNT_STATUS","PROFILE"};
        ArrayList<User> t=x.LayDSUser();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getUSERNAME(),t.get(i).getCREATED(),t.get(i).getEXPIRY_DATE(),t.get(i).getACCOUNT_STATUS(),t.get(i).getPROFILE()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();

    }//GEN-LAST:event_btn_userActionPerformed

    private void btnTableSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableSpaceActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thông tin TableSpace");
        String col[]={"USERNAME","TABLESPACE"};
        ArrayList<User> t=x.LayDSUserTableSpace();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getUSERNAME(),t.get(i).getDEFAULT_TABLESPACE()};
            dtm.addRow(obj);

        }
        tbDS.setModel(dtm);
        tbDS.updateUI();
    }//GEN-LAST:event_btnTableSpaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmHeThong dialog = new frmHeThong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPolicy;
    private javax.swing.JButton btnPolicyHienCo;
    private javax.swing.JButton btnSLSession;
    private javax.swing.JButton btnTableSpace;
    private javax.swing.JButton btn_database;
    private javax.swing.JButton btn_datafile;
    private javax.swing.JButton btn_instance;
    private javax.swing.JButton btn_pga;
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_session;
    private javax.swing.JButton btn_sga1;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDS;
    // End of variables declaration//GEN-END:variables
}
