/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.KhachHangDAO;
import dao.TruyVan;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.KhachHang;

/**
 *
 * @author nbkha
 */
public class frmKhachHang extends javax.swing.JDialog {

    /**
     * Creates new form frmKhachHang
     */
    KhachHangDAO x = new KhachHangDAO();

    public frmKhachHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Khách Hàng");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMakh = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        bnTim = new javax.swing.JButton();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblTenKH = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        txtGT = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNS = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        bnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        bnSua = new javax.swing.JButton();
        bnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSKH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Khách Hàng");

        lblMakh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMakh.setText("Tìm Mã Khách Hàng");

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        bnTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnTim.setForeground(new java.awt.Color(255, 102, 102));
        bnTim.setText("Tìm kiếm");
        bnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnTimActionPerformed(evt);
            }
        });

        lblMaKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaKH.setText("Mã Khách Hàng");

        txtMaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTenKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenKH.setText("Tên Khách Hàng");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGioiTinh.setText("Giới tính");

        txtGT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");

        txtNS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSDT.setText("SĐT");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnThem.setForeground(new java.awt.Color(255, 102, 102));
        bnThem.setText("Thêm");
        bnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        bnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnSua.setForeground(new java.awt.Color(255, 102, 102));
        bnSua.setText("Sửa");
        bnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSuaActionPerformed(evt);
            }
        });

        bnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnThoat.setForeground(new java.awt.Color(255, 102, 102));
        bnThoat.setText("Thoát");
        bnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnThoatActionPerformed(evt);
            }
        });

        tbDSKH.setBackground(new java.awt.Color(204, 204, 204));
        tbDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDSKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDSKH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(bnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenKH)
                            .addComponent(lblMaKH)
                            .addComponent(lblGioiTinh)
                            .addComponent(lblNgaySinh)
                            .addComponent(lblSDT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDT)
                            .addComponent(txtNS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMakh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bnTim, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKH)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKH)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(txtGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgaySinh)
                            .addComponent(txtNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnTimActionPerformed
        // TODO add your handling code here:
        String col[] = {"Mã KH", "Tên KH", "Giới Tính", "Ngày Sinh", "SĐT"};
        ArrayList<KhachHang> t = x.Timkiem(txtTim.getText());
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
        for (int i = 0; i < t.size(); i++) {
            Object[] obj = {t.get(i).getMaKhachHang(), t.get(i).getTenKhachHang(), t.get(i).getGioiTinh(), t.get(i).getNgaySinh(), t.get(i).getSoDienThoai()};
            dtm.addRow(obj);

        }
        tbDSKH.setModel(dtm);
        tbDSKH.updateUI();
    }//GEN-LAST:event_bnTimActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void tbDSKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSKHMouseClicked
        // TODO add your handling code here:
        int row = tbDSKH.getSelectedRow();
        this.txtMaKH.setText((String) tbDSKH.getValueAt(row, 0).toString().trim());
        this.txtTenKH.setText((String) tbDSKH.getValueAt(row, 1).toString().trim());
        this.txtGT.setText((String) tbDSKH.getValueAt(row, 2).toString().trim());
        this.txtNS.setText((String) tbDSKH.getValueAt(row, 3).toString().trim());
        this.txtSDT.setText((String) tbDSKH.getValueAt(row, 4).toString().trim());

    }//GEN-LAST:event_tbDSKHMouseClicked

    private void bnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnThemActionPerformed
        // TODO add your handling code here:
        if (txtMaKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng");
            return;
        }
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm khách hàng mới không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            if (ktTrungMa(txtMaKH.getText()) == true) {
                JOptionPane.showMessageDialog(this, "Đã tồn tại mã khách hàng này. Vui lòng chọn mã khác ");
                return;
            }
            KhachHang kh = new KhachHang();
            kh.setMaKhachHang(txtMaKH.getText().trim());
            kh.setTenKhachHang(txtTenKH.getText().trim());
            kh.setGioiTinh(txtGT.getText().trim());
            kh.setNgaySinh(txtNS.getText().trim());
            kh.setSoDienThoai(txtSDT.getText().trim());

            x.Them(kh);
            updateTable();
            JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công");
            xoatrang();
        }
    }//GEN-LAST:event_bnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (txtMaKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng");
            return;
        }
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa khách hàng này không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            if (ktTrungMa(txtMaKH.getText()) == false) {
                JOptionPane.showMessageDialog(this, "Không có mã khách hàng này. Vui lòng nhập mã khác ");
                return;
            }
            KhachHang kh = new KhachHang();
            kh.setMaKhachHang(txtMaKH.getText());
            x.Xoa(kh);
            updateTable();
            JOptionPane.showMessageDialog(this, "Bạn đã xóa thành công");
            xoatrang();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void bnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSuaActionPerformed
        // TODO add your handling code here:
        if (txtMaKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng");
            return;
        }
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật khách hàng này không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            if (ktTrungMa(txtMaKH.getText()) == true) {
                KhachHang kh = new KhachHang();
                kh.setMaKhachHang(txtMaKH.getText().trim());
                kh.setTenKhachHang(txtTenKH.getText().trim());
                kh.setGioiTinh(txtGT.getText().trim());
                kh.setNgaySinh(txtNS.getText().trim());
                kh.setSoDienThoai(txtSDT.getText().trim());
                x.Sua(kh);
                updateTable();
                JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công");
                xoatrang();
            } else {
                KhachHang kh = new KhachHang();
                kh.setMaKhachHang(txtMaKH.getText().trim());
                kh.setTenKhachHang(txtTenKH.getText().trim());
                kh.setGioiTinh(txtGT.getText().trim());
                kh.setNgaySinh(txtNS.getText().trim());
                kh.setSoDienThoai(txtSDT.getText().trim());
                x.Them(kh);
                updateTable();
                JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công");
                xoatrang();
            }

        }
    }//GEN-LAST:event_bnSuaActionPerformed

    private void bnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnThoatActionPerformed
        // TODO add your handling code here:
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã thoát thành công");
            this.setVisible(false);

        }
    }//GEN-LAST:event_bnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmKhachHang dialog = new frmKhachHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void updateTable() {
        String col[] = {"Mã KH", "Tên KH", "Giới Tính", "Ngày Sinh", "SĐT"};
        ArrayList<KhachHang> t = x.LayDS();
        DefaultTableModel dtm = new DefaultTableModel(col, 0);
        for (int i = 0; i < t.size(); i++) {
            Object[] obj = {t.get(i).getMaKhachHang(), t.get(i).getTenKhachHang(), t.get(i).getGioiTinh(), t.get(i).getNgaySinh(), t.get(i).getSoDienThoai()};
            dtm.addRow(obj);

        }

        tbDSKH.setModel(dtm);
        tbDSKH.updateUI();
    }

    private void xoatrang() {

        txtGT.setText("");
        txtMaKH.setText("");
        txtNS.setText("");
        txtSDT.setText("");
        txtTenKH.setText("");
        txtMaKH.requestFocus();
    }

    private boolean ktTrungMa(String ma) {

        try {
            String sql = "select makh from khachhang where makh='" + ma + "'";
            TruyVan provider = new TruyVan();
            provider.open();
            ResultSet rs = provider.executeQuery(sql);
            if (rs.next()) {
                return true;
            }
            return false;

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnSua;
    private javax.swing.JButton bnThem;
    private javax.swing.JButton bnThoat;
    private javax.swing.JButton bnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMakh;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JTable tbDSKH;
    private javax.swing.JTextField txtGT;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNS;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
