/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.PQDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pojo.PhanQuyen;
import pojo.User;
/**
 *
 * @author nbkha
 */
public class frmPhanQuyen extends javax.swing.JDialog {

    /**
     * Creates new form frmPhanQuyen
     */
    PQDAO x= new PQDAO();
    public frmPhanQuyen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Phân Quyền");
        this.setLocationRelativeTo(null);
        loadtbDS1();
//        loadtbDS2();
        cbboxTen();
        cbboxQuyen();
//        cbboxTenRole();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboTenUser = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboTenQuyen = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JButton();
        btnThuHoi = new javax.swing.JButton();
        btnThemQuyen = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDS1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quản Lý Phân Quyền");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tên User");

        cboTenUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTenUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên Quyền:");

        cboTenQuyen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 102, 102));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThuHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThuHoi.setForeground(new java.awt.Color(255, 102, 102));
        btnThuHoi.setText("Thu Hồi");
        btnThuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuHoiActionPerformed(evt);
            }
        });

        btnThemQuyen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemQuyen.setForeground(new java.awt.Color(255, 102, 102));
        btnThemQuyen.setText("Thêm ");
        btnThemQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemQuyenActionPerformed(evt);
            }
        });

        tbDS1.setBackground(new java.awt.Color(204, 204, 204));
        tbDS1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbDS1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(cboTenQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(btnThuHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboTenUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTenUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTenQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThuHoi)
                    .addComponent(btnTim))
                .addGap(18, 18, 18)
                .addComponent(btnThemQuyen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Phân Quyền", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemQuyenActionPerformed
        // TODO add your handling code here:
        PhanQuyen pq=new PhanQuyen();
        pq.setPRIVILEGE(cboTenQuyen.getSelectedItem().toString().trim());
        pq.setGRANTEE(cboTenUser.getSelectedItem().toString().trim());
        x.ThemQuyenUser(pq);
        loadtbDS1();
        JOptionPane.showMessageDialog(this, "Bạn đã thêm quyền thành công");
    }//GEN-LAST:event_btnThemQuyenActionPerformed

    private void btnThuHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuHoiActionPerformed
        // TODO add your handling code here:
        PhanQuyen pq=new PhanQuyen();
        pq.setPRIVILEGE(cboTenQuyen.getSelectedItem().toString().trim());
        pq.setGRANTEE(cboTenUser.getSelectedItem().toString().trim());
        x.ThuHoiQuyen(pq);
        loadtbDS1();
        JOptionPane.showMessageDialog(this, "Bạn đã thu hồi quyền thành công");
    }//GEN-LAST:event_btnThuHoiActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String col[]={"GRANTEE  ","PRIVILEGE"};
        ArrayList<PhanQuyen> t=x.LayDStheoTen(cboTenUser.getSelectedItem().toString());
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getGRANTEE(),t.get(i).getPRIVILEGE()};
            dtm.addRow(obj);

        }
        tbDS1.setModel(dtm);
        tbDS1.updateUI();
    }//GEN-LAST:event_btnTimActionPerformed

    private void cboTenUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTenUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPhanQuyen dialog = new frmPhanQuyen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void loadtbDS1() {
        String col[]={"GRANTEE ","PRIVILEGE"};
        ArrayList<PhanQuyen> t=x.LayDS();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getGRANTEE(),t.get(i).getPRIVILEGE()};
            dtm.addRow(obj);
            
        }
        tbDS1.setModel(dtm);
        tbDS1.updateUI();
    }

/*    private void loadtbDS2() {
        String col[]={"Role","PRIVILEGE"};
        ArrayList<PhanQuyen> t=x.LayDSRole();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getROLE(),t.get(i).getROLEID()};
            dtm.addRow(obj);
            
        }
        tbDS2.setModel(dtm);
        tbDS2.updateUI();
    }
    */
    private void cbboxTen() {
        ArrayList<User> dsCBTen=x.LayCBTen();
        DefaultComboBoxModel dcmPF=(DefaultComboBoxModel)cboTenUser.getModel();     
        for(User aa:dsCBTen)
        {
           dcmPF.addElement(aa.getUSERNAME());
        }
        cboTenUser.setModel(dcmPF);
    }
/*     private void cbboxTenRole() {
        ArrayList<PhanQuyen> dsCBTenRole=x.LayCBTenRole();
        DefaultComboBoxModel dcmPF=(DefaultComboBoxModel)cboTenNQ.getModel();     
        for(PhanQuyen aa:dsCBTenRole)
        {
           dcmPF.addElement(aa.getROLE());
        }
        cboTenNQ.setModel(dcmPF);        
    }
*/
    private void cbboxQuyen() {
        ArrayList<PhanQuyen> dsCBQuyen=x.LayCBQuyen();
        DefaultComboBoxModel dcmPF1=(DefaultComboBoxModel)cboTenQuyen.getModel();     
        for(PhanQuyen aa:dsCBQuyen)
        {
           dcmPF1.addElement(aa.getPRIVILEGE());
        }
        cboTenQuyen.setModel(dcmPF1);
//        cboQuyen1.setModel(dcmPF1);
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemQuyen;
    private javax.swing.JButton btnThuHoi;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboTenQuyen;
    private javax.swing.JComboBox<String> cboTenUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbDS1;
    // End of variables declaration//GEN-END:variables
}
