/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.PGADAO;
import dao.ProFileDAO;
import dao.TruyVan;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Profile;
import pojo.Profile1;
import pojo.User;
/**
 *
 * @author nbkha
 */
public class frmProfile extends javax.swing.JDialog {

    /**
     * Creates new form frmProFile
     */
    ProFileDAO x=new ProFileDAO();
    PGADAO y=new PGADAO();
    public frmProfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("ProFile And User");
        initComponents();
        uploadtable();
        uploadtable1();
        cbbox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUserPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblUserProfile = new javax.swing.JLabel();
        cboPF = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSUser = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblProFile4 = new javax.swing.JLabel();
        txtPF1 = new javax.swing.JTextField();
        lblProFile1 = new javax.swing.JLabel();
        txtPF2 = new javax.swing.JTextField();
        lblProFile2 = new javax.swing.JLabel();
        txtPF3 = new javax.swing.JTextField();
        lblProFile3 = new javax.swing.JLabel();
        txtPF4 = new javax.swing.JTextField();
        lblProfile4 = new javax.swing.JLabel();
        txtPF5 = new javax.swing.JTextField();
        btnThemPF = new javax.swing.JButton();
        btnXoaPF = new javax.swing.JButton();
        btnSuaPF = new javax.swing.JButton();
        btnTimPF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDSProFile = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hồ Sơ Người Dùng");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserName.setText("Tên User");

        lblUserPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserPass.setText("Mật khẩu");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        lblUserProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserProfile.setText("ProFile");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 102, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 102, 102));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnSua1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua1.setForeground(new java.awt.Color(255, 102, 102));
        btnSua1.setText("Tìm");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        tbDSUser.setBackground(new java.awt.Color(204, 204, 204));
        tbDSUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDSUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDSUser);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblUserName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblUserPass)
                                    .addGap(7, 7, 7)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUserProfile)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPass)
                            .addComponent(txtName)
                            .addComponent(cboPF, 0, 225, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserPass)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserProfile)
                            .addComponent(cboPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(btnSua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("User", jPanel2);

        lblProFile4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProFile4.setText("Tên ProFile");

        lblProFile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProFile1.setText("Số lần kết nối hỏng");

        lblProFile2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProFile2.setText("Số ngày khóa sau HSD");

        lblProFile3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProFile3.setText("Hạn sử dụng ");

        lblProfile4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProfile4.setText("Gia hạn việc đổi pass");

        btnThemPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemPF.setForeground(new java.awt.Color(255, 102, 102));
        btnThemPF.setText("Thêm");
        btnThemPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPFActionPerformed(evt);
            }
        });

        btnXoaPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaPF.setForeground(new java.awt.Color(255, 102, 102));
        btnXoaPF.setText("Xóa");
        btnXoaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPFActionPerformed(evt);
            }
        });

        btnSuaPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSuaPF.setForeground(new java.awt.Color(255, 102, 102));
        btnSuaPF.setText("Sửa");
        btnSuaPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPFActionPerformed(evt);
            }
        });

        btnTimPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimPF.setForeground(new java.awt.Color(255, 102, 102));
        btnTimPF.setText("Tim");
        btnTimPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimPFActionPerformed(evt);
            }
        });

        tbDSProFile.setBackground(new java.awt.Color(204, 204, 204));
        tbDSProFile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDSProFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSProFileMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDSProFile);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProFile1)
                            .addComponent(lblProFile2)
                            .addComponent(lblProFile3)
                            .addComponent(lblProfile4)
                            .addComponent(lblProFile4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPF4)
                            .addComponent(txtPF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtPF2)
                            .addComponent(txtPF3)
                            .addComponent(txtPF5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnSuaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThemPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProFile4)
                    .addComponent(txtPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProFile1)
                    .addComponent(txtPF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProFile2)
                    .addComponent(txtPF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProFile3)
                    .addComponent(txtPF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfile4)
                    .addComponent(txtPF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaPF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSuaPF, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnTimPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Profile", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Profile pf=new Profile();
        pf.setName(txtName.getText().trim());
        pf.setMatKhau(txtPass.getText().trim());
        x.ThemUser(pf);
        uploadtable();
        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công");

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        Profile pf=new Profile();
        pf.setName(txtName.getText().trim());
        x.XoaUser(pf);
        uploadtable();
        JOptionPane.showMessageDialog(this, "Bạn đã xóa thành công");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        Profile pf=new Profile();
        pf.setName(txtName.getText().trim());
        pf.setTenProfile(cboPF.getSelectedItem().toString().trim());
        x.SuaUser(pf);
        uploadtable();
        JOptionPane.showMessageDialog(this, "Bạn đã sửa thành công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        String col[]={"USERNAME","PROFILE"};
        ArrayList<User> t=y.LayDSUser2(txtName.getText());
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getUSERNAME(),t.get(i).getPROFILE()};
            dtm.addRow(obj);

        }
        tbDSUser.setModel(dtm);
        tbDSUser.updateUI();
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void tbDSUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSUserMouseClicked
        // TODO add your handling code here:
        int row=tbDSUser.getSelectedRow();
        this.txtName.setText((String)tbDSUser.getValueAt(row, 0).toString().trim());

    }//GEN-LAST:event_tbDSUserMouseClicked

    private void btnThemPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPFActionPerformed
        // TODO add your handling code here:
        Profile1 pf=new Profile1();
        pf.setProfile(txtPF1.getText().trim());
        pf.setSplanketnoihong(Integer.parseInt(txtPF2.getText().trim()));
        pf.setSongayhkoa(Integer.parseInt(txtPF3.getText().trim()));
        pf.setHansudung(Integer.parseInt(txtPF4.getText().trim()));
        pf.setGiahandoipass(Integer.parseInt(txtPF5.getText().trim()));
        x.ThemProFile(pf);
        cboPF.removeAllItems();
        cbbox();
        uploadtable();
        uploadtable1();
        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công");
    }//GEN-LAST:event_btnThemPFActionPerformed

    private void btnXoaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPFActionPerformed
        // TODO add your handling code here:
        Profile1 pf=new Profile1();
        pf.setProfile(txtPF1.getText().trim());
        x.XoaProFile(pf);
        cboPF.removeAllItems();
        cbbox();
        uploadtable();
        uploadtable1();
        JOptionPane.showMessageDialog(this, "Bạn đã xóa Profile thành công");

    }//GEN-LAST:event_btnXoaPFActionPerformed

    private void btnSuaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPFActionPerformed
        // TODO add your handling code here:
        Profile1 pf=new Profile1();
        pf.setProfile(txtPF1.getText().trim());
        pf.setSplanketnoihong(Integer.parseInt(txtPF2.getText().trim()));
        pf.setSongayhkoa(Integer.parseInt(txtPF3.getText().trim()));
        pf.setHansudung(Integer.parseInt(txtPF4.getText().trim()));
        pf.setGiahandoipass(Integer.parseInt(txtPF5.getText().trim()));
        x.SuaProFile(pf);
        cboPF.removeAllItems();
        cbbox();
        uploadtable();
        uploadtable1();
        JOptionPane.showMessageDialog(this, "Bạn đã sửa ProFile thành công");

    }//GEN-LAST:event_btnSuaPFActionPerformed

    private void btnTimPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimPFActionPerformed
        // TODO add your handling code here:
        String col[]={"PROFILE","resource_name","limit"};
        ArrayList<Profile1> t=x.TimKiemProFile(txtPF1.getText().trim());
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getProfile(),t.get(i).getResource_name(),t.get(i).getLimit()};
            dtm.addRow(obj);

        }
        txtPF1.setText("");
        tbDSProFile.setModel(dtm);
        tbDSProFile.updateUI();
    }//GEN-LAST:event_btnTimPFActionPerformed

    private void tbDSProFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSProFileMouseClicked
        // TODO add your handling code here:
        int row=tbDSProFile.getSelectedRow();
        this.txtPF1.setText((String)tbDSProFile.getValueAt(row, 0).toString().trim());
    }//GEN-LAST:event_tbDSProFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmProfile dialog = new frmProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private boolean ktUser(String user)
    {
        
         try {
            String sql="select username from dba_users where username='"+user+"'";
            TruyVan provider=new TruyVan();
            provider.open();
            ResultSet rs=provider.executeQuery(sql);
            if(rs.next())
            {
               return true;
            }
            return false;
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
         return false;
    }

        private void uploadtable() {       
        String col[]={"USERNAME","PROFILE"};
        ArrayList<User> t=y.LayDSUser1();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getUSERNAME(),t.get(i).getPROFILE()};
            dtm.addRow(obj);
            
        }
        tbDSUser.setModel(dtm);
        tbDSUser.updateUI();
    }

    private void uploadtable1() {
        String col[]={"PROFILE","resource_name","limit"};
        ArrayList<Profile1> t=x.LayDSProFile();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getProfile(),t.get(i).getResource_name(),t.get(i).getLimit()};
            dtm.addRow(obj);
            
        }
        tbDSProFile.setModel(dtm);
        tbDSProFile.updateUI();
    }
    private void cbbox() {
        ArrayList<Profile1> dsCBPF=x.LayCBProFile();
        DefaultComboBoxModel dcmPF=(DefaultComboBoxModel)cboPF.getModel();     
        for(Profile1 aa:dsCBPF)
        {
           dcmPF.addElement(aa.getProfile());
        }
        cboPF.setModel(dcmPF);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSuaPF;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemPF;
    private javax.swing.JButton btnTimPF;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaPF;
    private javax.swing.JComboBox<String> cboPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblProFile1;
    private javax.swing.JLabel lblProFile2;
    private javax.swing.JLabel lblProFile3;
    private javax.swing.JLabel lblProFile4;
    private javax.swing.JLabel lblProfile4;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPass;
    private javax.swing.JLabel lblUserProfile;
    private javax.swing.JTable tbDSProFile;
    private javax.swing.JTable tbDSUser;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPF1;
    private javax.swing.JTextField txtPF2;
    private javax.swing.JTextField txtPF3;
    private javax.swing.JTextField txtPF4;
    private javax.swing.JTextField txtPF5;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
