/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dao.SanPhamDAO;
import dao.TruyVan;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.NhaCungCap;
import pojo.SanPham;

/**
 *
 * @author nbkha
 */
public class frmSanPham extends javax.swing.JDialog {

    /**
     * Creates new form frmSanPham
     */
    SanPhamDAO x=new SanPhamDAO();
    public frmSanPham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Sản Phẩm ");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        updateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMancc = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lblMaSP = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        lblDVT = new javax.swing.JLabel();
        txtDVT = new javax.swing.JTextField();
        lblSL = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        lblDonGiaBan = new javax.swing.JLabel();
        txtDonGiaBan = new javax.swing.JTextField();
        lblDonGiaMua = new javax.swing.JLabel();
        txtDonGiaMua = new javax.swing.JTextField();
        lblMaNCC = new javax.swing.JLabel();
        txtNCC = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSSP = new javax.swing.JTable();
        lblLoaiSanPham = new javax.swing.JLabel();
        txtLoaiSanPham = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Sản Phẩm");

        lblMancc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMancc.setText("Tìm Sản Phẩm");

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 102, 102));
        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        lblMaSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaSP.setText("Mã sản phẩm");

        txtMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTenSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenSP.setText("Tên sản phẩm");

        txtTenSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanPhamActionPerformed(evt);
            }
        });

        lblDVT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDVT.setText("Đơn vị");

        txtDVT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSL.setText("Số lượng");

        txtSL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblDonGiaBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonGiaBan.setText("Đơn giá bán");

        txtDonGiaBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblDonGiaMua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonGiaMua.setText("Đơn giá mua");

        txtDonGiaMua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblMaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaNCC.setText("Mã NCC");

        txtNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 102, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 102, 102));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 102, 102));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tbDSSP.setBackground(new java.awt.Color(204, 204, 204));
        tbDSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDSSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDSSP);

        lblLoaiSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoaiSanPham.setText("Loại sản phẩm");

        txtLoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDonGiaMua)
                                    .addComponent(lblDonGiaBan)
                                    .addComponent(lblMaNCC)
                                    .addComponent(lblSL)
                                    .addComponent(lblDVT)
                                    .addComponent(lblTenSP))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenSanPham)
                                    .addComponent(txtDVT)
                                    .addComponent(txtSL)
                                    .addComponent(txtDonGiaMua, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonGiaBan)
                                    .addComponent(txtNCC)
                                    .addComponent(txtLoaiSanPham)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLoaiSanPham)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaSP)
                                .addGap(24, 24, 24)
                                .addComponent(txtMaSanPham)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMancc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(358, 358, 358)
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTim)
                            .addComponent(lblMancc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDonGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblDonGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNCC)
                            .addComponent(lblMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoaiSanPham))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String col[]={"Mã SP","Tên SP","DVT","SL","Đơn giá bán ","Đơn giá mua","MaNcc","Loại sản phẩm"};
        ArrayList<SanPham> t=x.TimKiem(txtTim.getText());
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getMaSanPham(),t.get(i).getTenSanPham(),t.get(i).getDonViTinh()
                ,t.get(i).getSoLuong(),t.get(i).getDonGiaBan(),t.get(i).getDonGiaMua()
                ,t.get(i).getMaNhaCungCap(),t.get(i).getLoaiSanPham()};
            dtm.addRow(obj);

        }
        tbDSSP.setModel(dtm);
        tbDSSP.updateUI();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //         TODO add your handling code here:
        if(txtMaSanPham.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sản phẩm");
            return;
        }
        int kq=JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm  sản phẩm không","Thông báo",JOptionPane.YES_NO_OPTION);
        if(kq==JOptionPane.YES_OPTION)
        {
            if(ktTrungMa(txtMaSanPham.getText())==true)
            {
                JOptionPane.showMessageDialog(this, "Đã tồn tại mã sản phẩm này. Vui lòng chọn mã khác ");
                return;
            }
            SanPham sp=new SanPham();
            sp.setMaSanPham(txtMaSanPham.getText().trim());
            sp.setTenSanPham(txtTenSanPham.getText().trim());
            sp.setDonViTinh(txtDVT.getText().trim());
            sp.setSoLuong(Integer.parseInt(txtSL.getText().trim()));
            sp.setDonGiaBan(Integer.parseInt(txtDonGiaBan.getText().trim()));
            sp.setDonGiaMua(Integer.parseInt(txtDonGiaMua.getText().trim()));
            sp.setMaNhaCungCap(txtNCC.getText().trim());
            sp.setLoaiSanPham(txtLoaiSanPham.getText().trim());
            x.Them(sp);
            updateTable();
            JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công ");
            xoatrang();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(txtMaSanPham.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sản phẩm");
            return;
        }
        int kq=JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa  sản phẩm không","Thông báo",JOptionPane.YES_NO_OPTION);
        if(kq==JOptionPane.YES_OPTION)
        {
            if(ktTrungMa(txtMaSanPham.getText())==false)
            {
                JOptionPane.showMessageDialog(this, "Không mã sản phẩm này. Vui lòng chọn mã khác ");
                return;
            }
            SanPham sp=new SanPham();
            sp.setMaSanPham(txtMaSanPham.getText());
            x.Xoa(sp);
            updateTable();
            JOptionPane.showMessageDialog(this, "Bạn đã xóa thành công ");
            xoatrang();

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(txtMaSanPham.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sản phẩm");
            return;
        }
        int kq=JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật  sản phẩm không","Thông báo",JOptionPane.YES_NO_OPTION);
        if(kq==JOptionPane.YES_OPTION)
        {
            if(ktTrungMa(txtMaSanPham.getText())==true)
            {
                SanPham sp=new SanPham();
                sp.setMaSanPham(txtMaSanPham.getText().trim());
                sp.setTenSanPham(txtTenSanPham.getText().trim());
                sp.setDonViTinh(txtDVT.getText().trim());
                sp.setSoLuong(Integer.parseInt(txtSL.getText().trim()));
                sp.setDonGiaBan(Integer.parseInt(txtDonGiaBan.getText().trim()));
                sp.setDonGiaMua(Integer.parseInt(txtDonGiaMua.getText().trim()));
                sp.setMaNhaCungCap(txtNCC.getText().trim());
                sp.setLoaiSanPham(txtLoaiSanPham.getText().trim());
                x.Sua(sp);
                updateTable();
                JOptionPane.showMessageDialog(this, "bạn đã cập nhật thành công ");
                xoatrang();
            }
            else
            {
                SanPham sp=new SanPham();
                sp.setMaSanPham(txtMaSanPham.getText().trim());
                sp.setTenSanPham(txtTenSanPham.getText().trim());
                sp.setDonViTinh(txtDVT.getText().trim());
                sp.setSoLuong(Integer.parseInt(txtSL.getText().trim()));
                sp.setDonGiaBan(Integer.parseInt(txtDonGiaBan.getText().trim()));
                sp.setDonGiaMua(Integer.parseInt(txtDonGiaMua.getText().trim()));
                sp.setMaNhaCungCap(txtNCC.getText().trim());
                sp.setLoaiSanPham(txtLoaiSanPham.getText().trim());
                x.Them(sp);
                updateTable();
                JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công ");
                xoatrang();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int kq=JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không","Thông báo",JOptionPane.YES_NO_OPTION);
        if(kq==JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(this, "Bạn đã thoát thành công");
            this.setVisible(false);

        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tbDSSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSSPMouseClicked
        // TODO add your handling code here:
        int row=tbDSSP.getSelectedRow();
        this.txtMaSanPham.setText((String)tbDSSP.getValueAt(row, 0).toString().trim());
        this.txtTenSanPham.setText((String)tbDSSP.getValueAt(row, 1).toString().trim());
        this.txtDVT.setText((String)tbDSSP.getValueAt(row, 2).toString().trim());
        this.txtSL.setText((int)tbDSSP.getValueAt(row, 3)+"".toString().trim());
        this.txtDonGiaBan.setText((int)tbDSSP.getValueAt(row, 4)+"".toString().trim());
        this.txtDonGiaMua.setText((int)tbDSSP.getValueAt(row, 5)+"".toString().trim());
        this.txtNCC.setText((String)tbDSSP.getValueAt(row, 6).toString().trim());
        this.txtLoaiSanPham.setText((String)tbDSSP.getValueAt(row, 7).toString().trim());
        //
    }//GEN-LAST:event_tbDSSPMouseClicked

    private void txtTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmSanPham dialog = new frmSanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void updateTable() {
        String col[]={"Mã SP","Tên SP","DVT","SL","Đơn giá bán ","Đơn giá mua","MaNcc","Loại san phẩm"};
        ArrayList<SanPham> t=x.LayDS();
        DefaultTableModel dtm=new DefaultTableModel(col,0);
        for(int i=0;i<t.size();i++)
        {
            Object []obj={t.get(i).getMaSanPham(),t.get(i).getTenSanPham(),t.get(i).getDonViTinh()
                    ,t.get(i).getSoLuong(),t.get(i).getDonGiaBan(),t.get(i).getDonGiaMua()
                    ,t.get(i).getMaNhaCungCap(),t.get(i).getLoaiSanPham()};
            dtm.addRow(obj);
            
        }
        tbDSSP.setModel(dtm);
        tbDSSP.updateUI();
    }
    private void xoatrang() {
        txtDVT.setText("");
        txtDonGiaBan.setText("");
        txtDonGiaMua.setText("");
        txtMaSanPham.setText("");
        txtNCC.setText("");
        txtSL.setText("");
        txtTenSanPham.setText("");
        txtMaSanPham.requestFocus();
        txtLoaiSanPham.setText("");
    }
    private boolean ktTrungMa(String ma)
    {
        
         try {
            String sql="select masp from sanpham where masp='"+ma+"'";
            TruyVan provider=new TruyVan();
            provider.open();
            ResultSet rs=provider.executeQuery(sql);
            if(rs.next())
            {
               return true;
            }
            return false;
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
         return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDVT;
    private javax.swing.JLabel lblDonGiaBan;
    private javax.swing.JLabel lblDonGiaMua;
    private javax.swing.JLabel lblLoaiSanPham;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMancc;
    private javax.swing.JLabel lblSL;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JTable tbDSSP;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtDonGiaBan;
    private javax.swing.JTextField txtDonGiaMua;
    private javax.swing.JTextField txtLoaiSanPham;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtNCC;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
